In [2]:
from sklearn.datasets import load_digits
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,log_loss,mean_absolute_error,mean_squared_error,accuracy_score,r2_score

In [3]:
dig=load_digits()
dig

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [4]:
X=dig["data"]
Y=dig["target"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
kn = KNeighborsClassifier(n_neighbors=2)
kn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [6]:
p=kn.predict(X_test)

In [7]:
print(classification_report(y_test,p))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        55
          1       0.96      1.00      0.98        55
          2       1.00      1.00      1.00        52
          3       0.95      1.00      0.97        56
          4       0.98      0.98      0.98        64
          5       0.99      1.00      0.99        73
          6       1.00      1.00      1.00        57
          7       1.00      0.98      0.99        62
          8       0.98      0.98      0.98        52
          9       0.98      0.91      0.95        68

avg / total       0.99      0.98      0.98       594



In [8]:
log.score(X_test,y_test)

NameError: name 'log' is not defined

In [9]:
mean_squared_error(y_test,p)

0.3569023569023569

In [12]:
print(confusion_matrix(y_test,p))

[[55  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0 56  0  0  0  0  0  0]
 [ 0  1  0  0 63  0  0  0  0  0]
 [ 0  0  0  0  0 73  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  1  0  0  0  0  0  0 51  0]
 [ 0  0  0  3  1  1  0  0  1 62]]


In [13]:
r2_score(y_test,p)

0.95575953716286

In [14]:
r2_score(y_test,p)

0.95575953716286

In [15]:
mean_absolute_error(y_test,p)

0.06734006734006734

In [16]:
accuracy_score(y_test,p)

0.9848484848484849