In [19]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
d = load_digits()
data= pd.DataFrame(d.data)
tar = pd.DataFrame(d.target)

In [21]:
data.head(5)

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [22]:
tar.head(5)

0
0  0
1  1
2  2
3  3
4  4

In [27]:
X=data
Y=tar

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=40)

In [29]:
s=SVC(kernel='linear', degree=4)
s.fit(X_train, y_train) 


C:\Users\acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
pred = s.predict(X_test)



In [32]:
print ("Confusion Matrix:\n",confusion_matrix(y_test, pred))
print ("\n\nClassification Report:\n", classification_report(y_test,pred))

Confusion Matrix:
 [[52  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 57  0  0  0  0  0  2]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  1  0 49  0  0  0  0]
 [ 0  1  0  0  0  0 63  0  0  0]
 [ 0  0  0  0  1  0  0 57  0  0]
 [ 0  4  0  0  0  0  0  0 64  0]
 [ 0  0  0  0  0  1  0  0  2 56]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        52
          1       0.94      0.97      0.95        74
          2       1.00      1.00      1.00        55
          3       0.98      0.97      0.97        59
          4       0.98      1.00      0.99        55
          5       0.98      0.98      0.98        50
          6       1.00      0.98      0.99        64
          7       1.00      0.98      0.99        58
          8       0.94      0.94      0.94        68
          9       0.97      0.95      0.96        59

avg / total       0.98      0.98      0

In [34]:
s  = SVC(kernel='sigmoid')  
s.fit(X_train, y_train) 
pr2 = s.predict(X_test)
print ("Confusion Matrix:\n",confusion_matrix(y_test, pr2))
print ("\n\nClassification Report:\n", classification_report(y_test, pr2))

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix:
 [[ 0  0  0  0  0 52  0  0  0  0]
 [ 0  0  0  0  0 74  0  0  0  0]
 [ 0  0  0  0  0 55  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0 55  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 0  0  0  0  0 64  0  0  0  0]
 [ 0  0  0  0  0 58  0  0  0  0]
 [ 0  0  0  0  0 68  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]]


Classification Report:
              precision    recall  f1-score   support

          0       0.00      0.00      0.00        52
          1       0.00      0.00      0.00        74
          2       0.00      0.00      0.00        55
          3       0.00      0.00      0.00        59
          4       0.00      0.00      0.00        55
          5       0.08      1.00      0.16        50
          6       0.00      0.00      0.00        64
          7       0.00      0.00      0.00        58
          8       0.00      0.00      0.00        68
          9       0.00      0.00      0.00        59

avg / total       0.01      0.08      0

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
s  = SVC(kernel='rbf')  
s.fit(X_train, y_train) 
pr3 = s.predict(X_test)
print ("Confusion Matrix:\n",confusion_matrix(y_test, pr3))
print ("\n\nClassification Report:\n", classification_report(y_test, pr3))

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix:
 [[27  0  0  0  0 25  0  0  0  0]
 [ 0 13  0  0  0 61  0  0  0  0]
 [ 0  0 12  0  0 43  0  0  0  0]
 [ 0  0  0 15  0 44  0  0  0  0]
 [ 0  0  0  0 25 30  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 0  0  0  0  0 34 30  0  0  0]
 [ 0  0  0  0  0 42  0 16  0  0]
 [ 0  0  0  0  0 67  0  0  1  0]
 [ 0  0  0  0  0 49  0  0  0 10]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      0.52      0.68        52
          1       1.00      0.18      0.30        74
          2       1.00      0.22      0.36        55
          3       1.00      0.25      0.41        59
          4       1.00      0.45      0.62        55
          5       0.11      1.00      0.20        50
          6       1.00      0.47      0.64        64
          7       1.00      0.28      0.43        58
          8       1.00      0.01      0.03        68
          9       1.00      0.17      0.29        59

avg / total       0.93      0.34      0

In [36]:
s  = SVC(kernel='poly')  
s.fit(X_train, y_train) 
pr4 = s.predict(X_test)
print ("Confusion Matrix:\n",confusion_matrix(y_test, pr4))
print ("\n\nClassification Report:\n", classification_report(y_test, pr4))

Confusion Matrix:
 [[52  0  0  0  0  0  0  0  0  0]
 [ 0 74  0  0  0  0  0  0  0  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 59  0  0  0  0  0  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 0  1  0  0  0  0 63  0  0  0]
 [ 0  0  0  0  0  0  0 58  0  0]
 [ 0  3  0  1  0  0  0  0 63  1]
 [ 0  0  0  0  0  0  0  0  0 59]]


Classification Report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        52
          1       0.95      1.00      0.97        74
          2       1.00      1.00      1.00        55
          3       0.98      1.00      0.99        59
          4       1.00      1.00      1.00        55
          5       1.00      1.00      1.00        50
          6       1.00      0.98      0.99        64
          7       1.00      1.00      1.00        58
          8       1.00      0.93      0.96        68
          9       0.98      1.00      0.99        59

avg / total       0.99      0.99      0

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
